### Teste Get Hello world

GET http://localhost:8080/forum

### Teste List Topicos
GET http://localhost:8080/forum/listarTopicos
Content-Type: application/json

### Teste Lista de Topicos filtrada por id
GET http://localhost:8080/forum/listarTopico/4
Content-Type: application/json

### Teste cadastro de topicos
POST http://localhost:8080/forum/cadastrar
Content-Type: application/json

{
  "id": 3,
  "titulo": "Bean Validation",
  "mensagem":"Teste Validation",
  "idCurso": 1,
  "idAutor": 1
}