### Teste Get Hello world

GET http://localhost:8080/forum/

### Teste List Topicos
GET http://localhost:8080/forum/topicos/listarTopicos
Content-Type: application/json

### Teste List Topicos filtrando por nome do curso
GET http://localhost:8080/forum/topicos/listarTopicos?nomeDoCurso=Kotlin
Content-Type: application/json

### Teste List Topicos filtrando por paginação
GET http://localhost:8080/forum/topicos/listarTopicos?size=2&sort=titulo
Content-Type: application/json

### Teste Lista de Topicos filtrada por id
GET http://localhost:8080/forum/topicos/listarTopico/2
Content-Type: application/json

### Teste Lista de relatorio
GET http://localhost:8080/forum/topicos/relatorio
Content-Type: application/json

### Teste cadastro de topicos
POST http://localhost:8080/forum/topicos/cadastrar
Content-Type: application/json

{
  "titulo": "Novo topico",
  "mensagem":"Novo topico",
  "idCurso": 2,
  "idAutor": 1
}

### Teste atualizar topico
PUT http://localhost:8080/forum/topicos/atualizar
Content-Type: application/json

{
  "id": 2,
  "titulo": "Testando metodo atualizar",
  "mensagem": "Testando putmapping"
}

### Teste Delete Topico
DELETE http://localhost:8080/forum/topicos/deletar/2