### Teste para listar os cursos
GET http://localhost:8080/forum/curso/listar

### Teste para cadastrar os cursos
POST http://localhost:8080/forum/curso/cadastrar
Content-Type: application/json

{
  "id": 6,
  "nome": "Teste Novo curso",
  "categoria": "Teste Nova categoria"
}

### Teste para atualizar os cursos
PUT http://localhost:8080/forum/curso/atualizar/3
Content-Type: application/json

{
  "nome": "Nome atualizado",
  "categoria": "Categoria atualizada"
}

### Teste para deletear um curso
DELETE http://localhost:8080/forum/curso/deletar/4